version: '3.2'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/symfony.demo
    working_dir: /var/www/symfony.demo
    ports:
      - "80:80"
    networks:
      main:
        aliases:
          - symfony.demo

  selenium:
    image: 'selenium/standalone-chrome-debug'
    volumes:
      - ./:/data
    ports:
      - "4444:4444"
      - "5900:5900"
    privileged: true
    networks:
      main:
        aliases:
          - selenium.demo

networks:
  main:
